---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-harbor
  namespace: harbor
spec:
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
      version: 1.8.2
  values:
    expose:
      tls:
        enabled: false
      ingress:
        annotations:
          ingress.kubernetes.io/ssl-redirect: "false"
    persistence:
      persistentVolumeClaim:
        registry:
          size: 20Gi
  valuesFrom:
    - kind: Secret
      name: harbor-secret
      valuesKey: admin-password
      targetPath: harborAdminPassword
      optional: true
  interval: 1m0s

