---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom-prom
  namespace: prom
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 3.0.0
  # values:
  #   service:
  #     type: "LoadBalancer"
  interval: 1m0s

