---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom-nats-exporter
  namespace: prom
spec:
  chart:
    spec:
      chart: prometheus-nats-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 2.9.3
  values:
    service:
      type: "LoadBalancer"
  interval: 1m0s

