apiVersion: v1
kind: Namespace
metadata:
  name: rentapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rentapp-pvc
  namespace: rentapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rentapp
  name: rentapp
  namespace: rentapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rentapp
    spec:
      volumes:
      - name: cachevol
        persistentVolumeClaim:
          claimName: rentapp-pvc
      - name: cacheconfig
        configMap:
          name: redis-config
          items:
          - key: redis-config
            path: redis.conf
      containers:
      - image: redis:6.2.6
        name: redis
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/etc/redis/
          name: cacheconfig
        - mountPath: /data
          name: cachevol
        args:
        - "redis-server"
        - "/usr/local/etc/redis/redis.conf"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rentapp
  name: rentapp
  namespace: rentapp
spec:
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: rentapp
  type: NodePort
status:
  loadBalancer: {}
