apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler-rstore
  namespace: rentapp
  # labels:
  #   app: crawler-rstore
spec:
  schedule: "4 0-14,22-23 * * *"
  jobTemplate:
    spec:
      # selector:
      #   matchLabels:
      #     app: crawler-rstore
      template:
        # metadata:
        #   labels:
        #     app: crawler-rstore
        spec:
          restartPolicy: OnFailure
          initContainers:
          - name: init-myservice
            image: busybox:1.28
            command: ['sh', '-c', 'until nc -z nats-server 4222; do echo waiting for nats-server; sleep 2; done;']
          - name: init-myservice2
            image: busybox:1.28
            command: ['sh', '-c', 'until nc -z cache-mgr 50051; do echo waiting for cache-mgr; sleep 2; done;']
          containers:
          - name: crawler-rstore
            image: local.insecure-registry.io/nekia/crawler-rstore:1.0.0
            imagePullPolicy: Always
            env:
              - name: NATS_SERVER_URL
                value: nats-server:4222
              - name: CACHE_MGR_URL
                value: cache-mgr:50051
            volumeMounts:
            - name: crawler-rstore-config-tky-rent
              mountPath: /usr/src/app/setting
              readOnly: true
          volumes:
          - name: crawler-rstore-config-tky-rent
            configMap:
              name: crawler-rstore-config-tky-rent
              items:
              - key: "setting.json"
                path: "setting.json"
          imagePullSecrets:
          - name: regcred