apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: crowling-sites
  namespace: rentapp
spec:
  schedule: "30 7-23/2 * * *"
  timezone: "Asia/Tokyo"   # Default to local machine timezone
  # startingDeadlineSeconds: 0
  concurrencyPolicy: "Forbid"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  # suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: step-step
    templates:
    - name: step-step
      steps:
      - - name: homes
          template: homes
          continueOn:
            failed: true
      - - name: suumo
          template: suumo
          continueOn:
            failed: true
      - - name: rstore
          template: rstore
          continueOn:
            failed: true
      - - name: linea
          template: linea
          continueOn:
            failed: true
    - name: homes
      container:
        image: local.insecure-registry.io/main:1.0.0
        imagePullPolicy: Always
        env:
          - name: NATS_SERVER_URL
            value: nats-server:4222
          - name: WATCHING_SITE_NAME
            value: "HOMES"
        command: [ "bash" ]
        args: ["-c","npm start"]
    - name: suumo
      container:
        image: local.insecure-registry.io/main:1.0.0
        imagePullPolicy: Always
        env:
          - name: NATS_SERVER_URL
            value: nats-server:4222
          - name: WATCHING_SITE_NAME
            value: "SUUMO"
        command: [ "bash" ]
        args: ["-c","npm start"]
    - name: rstore
      container:
        image: local.insecure-registry.io/main:1.0.0
        imagePullPolicy: Always
        env:
          - name: NATS_SERVER_URL
            value: nats-server:4222
          - name: WATCHING_SITE_NAME
            value: "R-STORE"
        command: [ "bash" ]
        args: ["-c","npm start"]
    - name: linea
      container:
        image: local.insecure-registry.io/main:1.0.0
        imagePullPolicy: Always
        env:
          - name: NATS_SERVER_URL
            value: nats-server:4222
          - name: WATCHING_SITE_NAME
            value: "LINEA"
        command: [ "bash" ]
        args: ["-c","npm start"]
    imagePullSecrets:
    - name: regcred
