# kustomization.yml
namespace: metallb-system

resources:
  - github.com/metallb/metallb//manifests?ref=v0.12.1

configMapGenerator:
- name: config
  files:
    - config

generatorOptions:
  disableNameSuffixHash: true