---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  chart:
    spec:
      chart: argo-workflows
      sourceRef:
        kind: HelmRepository
        name: argo-workflows
      version: 0.14.0
  values:
    server:
      extraArgs:
        - --auth-mode=server
    controller:
      containerRuntimeExecutor: "pns"
    singleNamespace: false
  interval: 1m0s
  targetNamespace: argo-workflows

