---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argo-workflows
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./argoproj/argo-workflows/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

