---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./harbor/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

