---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 4m0s
  path: ./metallb/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
