---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prom
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./prom/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
