---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: registry
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./registry/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

    