apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: container-image
spec:
  serviceAccountName: workflow
  templates:
  - name: build-kaniko-git
    inputs:
      parameters:
      - name: app_repo
      - name: container_image
      - name: short-sha
      - name: subpath
    container:
      image: gcr.io/kaniko-project/executor:debug
      command: [/kaniko/executor]
      args:
      - --context={{inputs.parameters.app_repo}}
      - --destination=192.168.0.133:30007/{{inputs.parameters.container_image}}:{{inputs.parameters.short-sha}}
      - --dockerfile={{inputs.parameters.subpath}}/Dockerfile
      - --insecure-registry=192.168.0.133:30007
      volumeMounts:
        - name: kanikoregcred
          mountPath: /kaniko/.docker/
