apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
  - name: test-dep
    eventSourceName: webhook
    eventName: example
    filters:
      data:
        - path: body.ref
          type: string
          value:
            - refs/heads/main
        - path: "[body.commits.#.modified.#()#, body.commits.#.added.#()#, body.commits.#.removed.#()#]"
          type: string
          value:
            - ".*main/.*"
            - ".*notifier/.*"
            - ".*scanner/.*"
            - ".*crawler/.*"
            - ".*areaInfoMgr/.*"
            - ".*cacheMgr/.*"
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: argo-workflows-demo-
              namespace: argo-events
            spec:
              entrypoint: script-test
              serviceAccountName: workflow
              arguments:
                parameters:
                - name: app_repo
                  value: git://github.com/
                - name: container_image
                  value: mediator
                - name: container_tag
                  value: "1.0.0"
                - name: subpath
                  value: "mediator"
              volumes:
              - name: kanikoregcred
                secret:
                  secretName: kanikoregcred
                  items:
                    - key: config.json
                      path: config.json
              templates:
              - name: script-test
                steps:
                - - name: cat-files
                    template: cat-files-script
                    arguments:
                      parameters:
                        - name: subpath-list
                          value: "{{workflow.parameters.subpath}}"
                - - name: build-subpath
                    template: build-subpath-script
                    arguments:
                      parameters:
                        - name: subpath
                          value: "{{item}}"
                        - name: app_repo
                          value: "{{workflow.parameters.app_repo}}"
                        - name: container_image
                          value: "{{=sprig.replace(item, ' ', '-'}}"
                        - name: container_tag
                          value: "{{workflow.parameters.container_tag}}"
                        - name: subpath
                          value: "{{workflow.parameters.subpath}}"

                    # withItems:
                    #   - Hello
                    #   - World
                    withParam: "{{steps.cat-files.outputs.parameters.subpath-list}}" 
              - name: cat-files-script
                inputs:
                  parameters:
                  - name: subpath-list
                script:
                  image: itchyny/gojq:0.12
                  command: [sh]
                  source: |                                         # Contents of the here-script
                    echo {{inputs.parameters.subpath-list}} | \
                      sed  -e 's/\[\[//' -e 's/\]\]//' | \
                      tr ',' '\n' | \
                      xargs -I{} dirname {} | \
                      sort -u | \
                      grep -v -E 'setting|protobuf' | \
                      tr '\n' ',' | \
                      sed -e 's/,$//' | \
                      /gojq -Rs 'split(",")' > /tmp/hello_world.txt
                    cat /tmp/hello_world.txt
                    echo Completed
                outputs:
                  parameters:
                  - name: subpath-list  # name of output parameter
                    valueFrom:
                      path: /tmp/hello_world.txt
              - name: print-files-script
                inputs:
                  parameters:
                  - name: subpath
                script:
                  image: debian:9.4
                  command: [bash]
                  source: |                                         # Contents of the here-script
                    echo {{inputs.parameters.subpath}}
              - name: build-subpath-script
                dag:
                  tasks:
                  - name: build
                    templateRef:
                      name: container-image
                      template: build-kaniko-git
                      clusterScope: true
                    arguments:
                      parameters:
                      - name: app_repo
                        value: "{{workflow.parameters.app_repo}}"
                      - name: container_image
                        value: "{{workflow.parameters.container_image}}"
                      - name: container_tag
                        value: "{{workflow.parameters.container_tag}}"
                      - name: subpath
                        value: "{{workflow.parameters.subpath}}"
        parameters:
        - src:
            dependencyName: test-dep
            dataKey: body.repository.full_name
          dest: spec.arguments.parameters.0.value
          operation: append
        - src:
            dependencyName: test-dep
            dataKey: body.commits.#.modified
          dest: spec.arguments.parameters.3.value
          operation: overwrite

