apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-events
resources:
  - eventbus-native.yaml
  - sensor-rbac.yaml
  - workflow-rbac.yaml
  # - argo-workflows-templates-build-kaniko-git.yaml
  - event-sources-github.yaml
  # - event-sensors-github.yaml
  - ngrok-deploy.yaml

configMapGenerator:
- name: ngrok-config
  files:
    # configfile is used as key
    - ngrok.yml