apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rentapp/app2
    repoURL: https://github.com/nekia/rent-watch-infra
    targetRevision: HEAD