---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo-cd
      version: 5.16.14
  values:
    # applicationSet:
    #   image:
    #     repository: ghcr.io/jr64/argocd-applicationset
    #     tag: v0.4.0
    configs:
      params:
        server.basehref: "/argocd"
        server.rootpath: "/argocd"
      cm:
        accounts.image-updater: apiKey
        accounts.testuser: apiKey, login
    # server:
    #   ingress:
    #     enabled: true
    #     hosts:
    #       - "foo.bar.com"
    #     ingressClassName: "nginx"
    #     paths:
    #       - "argocd"
  interval: 1m0s
