---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-events
  namespace: argo-events
spec:
  chart:
    spec:
      chart: argo-events
      sourceRef:
        kind: HelmRepository
        name: argo-events
      version: 1.13.0
  interval: 1m0s

